In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('/Users/avinashmacbookair/Documents/TREND Health Partners/Healthcare_ETL_Project/processed/Healthcare_Dataset.csv')
df.head()

,treatment_id,treatment_start_date,treatment_completion_date,treatment_outcome_status,treatment_outcome_date,treatment_duration,treatment_cost,treatment_type,provider_id,provider_name,...,age,disease_id,speciality_id_y,disease_name,disease_type,severity,transmission_mode,mortality_rate,added_at,modified_at
0,1,2024-01-01 00:00:00.000000000,2024-01-08 00:00:00.000000000,unsuccessful,2024-01-12 00:00:00.000000000,7,46489.71,pharmacological,1,Nandini Srivastava,...,71,38,8,Pneumonia,Infectious,Moderate,Airborne,0.10,2024-01-12 00:00:00.000000000,2024-01-12 00:00:00.000000000
1,2,2024-01-01 00:00:45.051492930,2024-01-05 00:00:45.051492930,partially successful,2024-01-07 00:00:45.051492930,4,29150.13,surgical,1,Nandini Srivastava,...,50,36,8,Bone Fractures,Acute,Moderate,Indirect contact,0.01,2024-01-07 00:00:45.051492930,2024-01-07 00:00:45.051492930
2,3,2024-01-01 00:01:30.102985861,2024-01-04 00:01:30.102985861,deceased,2024-01-10 00:01:30.102985861,3,34554.65,pharmacological,1,Nandini Srivastava,...,54,37,8,Tumors,Non-infectious,Severe,Indirect contact,0.20,2024-01-10 00:01:30.102985861,2024-01-10 00:01:30.102985861
3,4,2024-01-01 00:02:15.154478792,2024-01-08 00:02:15.154478792,worsened,2024-01-15 00:02:15.154478792,7,24743.59,surgical,1,Nandini Srivastava,...,78,40,8,Kidney Stones,Non-infectious,Moderate,Indirect contact,0.01,2024-01-15 00:02:15.154478792,2024-01-15 00:02:15.154478792
4,5,2024-01-01 00:03:00.205971722,2024-01-05 00:03:00.205971722,stable,2024-01-12 00:03:00.205971722,4,8095.13,preventive,1,Nandini Srivastava,...,32,37,8,Tumors,Non-infectious,Severe,Indirect contact,0.20,2024-01-12 00:03:00.205971722,2024-01-12 00:03:00.205971722

In [6]:
df.shape

(1050000, 30)

In [8]:
# Convert the 'treatment_outcome_date' column to datetime if it's not already
df['treatment_outcome_date'] = pd.to_datetime(df['treatment_outcome_date'])

# Extract the unique years from the 'treatment_outcome_date' column
unique_years = df['treatment_outcome_date'].dt.year.unique()

# Display the unique years
print("Unique years of treatment outcomes:", unique_years)

Unique years of treatment outcomes: [2024 2025]